name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      uses: lunarmodules/busted@v2.2.0
      with:
        args: --lpath=./lua/?.lua ./test

    - name: Run linter
      uses: lunarmodules/luacheck@v1.1.2
      with:
        args: . --globals vim

    - name: Verify formatting
      uses: JohnnyMorganz/stylua-action@v4.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .
        version: latest
